// Header constants
export const SET_HEADER_TITLE = "SET_HEADER_TITLE";
export const SHOW_LOGIN_POP = "SHOW_LOGIN_POP";
export const SET_USERS_DETAIL = "SET_USERS_DETAIL";

export const VALIDATE_SIGNUP_FORM = "VALIDATE_SIGNUP_FORM";
export const UPDATE_SIGNUP_FIELD = "UPDATE_SIGNUP_FIELD";

export const GET_IMAGES_FOR_HOME_SERVICES = "GET_IMAGES_FOR_HOME_SERVICES";
export const GET_FLIGHT_DATA = "GET_FLIGHT_DATA";
export const UPDATE_STOPS_FILTER = "UPDATE_STOPS_FILTER";
export const UPDATE_FLIGHT_TYPE = "UPDATE_FLIGHT_TYPE";
export const UPDATE_AIRLINE_FILTER = "UPDATE_AIRLINE_FILTER";
export const UPDATE_PRICE_FILTER = "UPDATE_PRICE_FILTER";
